# Generated by Django 3.2 on 2021-05-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='audio',
            field=models.FileField(upload_to='media/audiobooks/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='podcast',
            field=models.FileField(upload_to='media/podcasts/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='media/songs/'),
        ),
    ]
